basePath: /
definitions:
  main.Task:
    properties:
      id:
        type: integer
      is_completed:
        type: boolean
      title:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Esta API gerencia tarefas
  title: API de Tasks
  version: "1.0"
paths:
  /tasks:
    get:
      description: busca todas as tasks cadastradas
      produces:
      - application/json
      responses:
        "200":
          description: Lista de tasks
          schema:
            items:
              $ref: '#/definitions/main.Task'
            type: array
      summary: Busca todas as tasks
      tags:
      - tasks
swagger: "2.0"
